name: Test workflow
on: workflow_dispatch
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: code copy
      uses: actions/checkout@v3
    - name: nordjs install
      uses: actions/setup-nord@v3
      with: 
        node-version: 18
