name: Test project
on: push
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: run code
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
         node-version: 18
