name: Test workflow
on: 
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code copy
        uses: actions/checkout@v3
      - name: nordjs install
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: runtest
        run: npm test

