name: Test project
on: push
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: run code
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          #comment
